### ISSUE TITLE
发送 实例心跳 报错

### ISSUE THREAD

**Issue by nidiac** [workbunny/webman-nacos#11]
在 instance registerAsync 和 beat 需要把 ephemeral 转换成字符串，否会会造成参数失效的问题

参考 https://github.com/hyperf/hyperf/issues/4555

**Comment by chaz6chez** [comment]
ephemeral 参数我没有强制检查他的类型，所以用户传什么类型的参数值就是什么类型，我这里没有像hyperf一样做转换；
 如果使用了默认的注册进程，可以把配置文件app.php中对应的参数修改成字符串即可；随后配置文件我也会对应更新
