### ISSUE TITLE
案例中的database在nacos的配置中是什么？

### ISSUE THREAD

**Issue by TimeIsGoOn** [workbunny/webman-nacos#14]
情况如下，我本地的nacos可以使用http请求到内容
![image](https://github.com/workbunny/webman-nacos/assets/13595639/1d56ad5e-6e88-4ad7-b872-7b8134412586)

然后我用webman引入本项目后是这样的
![image](https://github.com/workbunny/webman-nacos/assets/13595639/4f8eb249-f3c5-4306-b174-533e97c20729)
结果是无法获取到值
![image](https://github.com/workbunny/webman-nacos/assets/13595639/ba8f3683-6972-4876-85da-c5663af5b11a)

我是参考文档
![image](https://github.com/workbunny/webman-nacos/assets/13595639/ea411431-2c4f-4088-a466-329d2fe05a2a)

请问我这里应该怎么写呢？

**Comment by TimeIsGoOn** [comment]
感谢已经解决了

workbunny/webman-nacos/src/Provider/ServiceProvider.php
![image](https://github.com/workbunny/webman-nacos/assets/13595639/891a6848-662a-48d7-b85e-54f3f31ccbf9)

不过我的返回值是这种格式的字符串，怎么转换成对象或者数组呢？

![image](https://github.com/workbunny/webman-nacos/assets/13595639/8efb0e69-234e-4d2c-80cf-39032ef7dda5)

**Comment by chaz6chez** [comment]
> 感谢已经解决了
> 
> workbunny/webman-nacos/src/Provider/ServiceProvider.php ![image](https://user-images.githubusercontent.com/13595639/278813940-891a6848-662a-48d7-b85e-54f3f31ccbf9.png)
> 
> 不过我的返回值是这种格式的字符串，怎么转换成对象或者数组呢？
> 
> ![image](https://user-images.githubusercontent.com/13595639/278814008-8efb0e69-234e-4d2c-80cf-39032ef7dda5.png)

通常来说，nacos储存的配置内容是自定义的，取决于格式本身，如果储存的是yaml格式，那么需要在获取到字符串信息后通过对应的格式转换来进行获取，比如yaml转数组，或者ini转数组
