### ISSUE TITLE
src/Client.php里使用的config函数为何只在tests/helpers.php里定义，使用时必须还得引入这个测试文件吗

### ISSUE THREAD

**Issue by hkui** [workbunny/webman-nacos#6]
Fatal error: Uncaught Error: Call to undefined function Workbunny\WebmanNacos\config() in /mnt/hgfs/myenv/data/www/cnblogs/php/nacos/vendor/workbunny/webman-nacos/src/Client.php:69
Stack trace:
#0 /mnt/hgfs/myenv/data/www/cnblogs/php/nacos/config.php(6): Workbunny\WebmanNacos\Client::channel()
#1 {main}

**Comment by chaz6chez** [comment]
已修复，调整了一种方式进行测试
