### ISSUE TITLE
关于请求超时时间的设置

### ISSUE THREAD

**Issue by krissss** [workbunny/webman-nacos#9]
问题：心跳接口按道理需要单独设置请求 timeout 时长，否则会造成以下场景问题
场景：如果一个心跳接口发出去了，由于网络等原因，导致超时响应了（不是超时失败，是超长时间后响应成功了），此时会导致nacos服务实例进行了一次掉线到上线的过程（会导致 weight 变为 0，见 #8 ）
临时解决：通过 #8 可以解决掉线到上线后导致 weight 为 0 的问题

最佳解决：心跳接口应该设置超时时间为心跳间隔

另外：目前我看了所有 httpclient 配置的 timeout 都是取的 `long_pulling_interval` 的时长，感觉有些不合理，应该仅针对那个接口设置 timeout，其他的接口最好使用默认的 php 超时时间，并提供一个全局的超时时间设置的地方

**Comment by chaz6chez** [comment]
thanks
